### ISSUE TITLE
Validation: Allow the same block name in different hw contexts 

### ISSUE THREAD

**Issue by MenezesM** [systemviewinc/visual-system-integrator#204]
Generate system has the following error when running with the same block name (IE vsi_gen_ip_0) in different HW blocks, this is not a valid error.

ERROR(50) VALIDATE: duplicate block names found:  {/vsi_platform/vc709/axi_mem_intercon_2} axi_mem_intercon_2: /vsi_platform/vcu_118
ERROR(50) VALIDATE: duplicate block names found:  {/vsi_system/vc709/vsi_gen_ip_0} vsi_gen_ip_0: /vsi_system/vcu_118

**Comment by udnaan** [comment]
Can you try dragging the block with identical names in the same context and see if it generates a valid system? 
If Vivado handles this case than I'm okay with getting rid of that error.

**Comment by MenezesM** [comment]
It looks like if I drag vsi_gen_ip_0 into a context that already has it then it will automatically change the name top vsi_gen_ip_1.

Dragging block across contexts in the platform doesn't make as much sense, but I can't seem to do it because of errors.

**Comment by udnaan** [comment]
It seems that an _1 is appended if the block is moved across hierarchy. The validation error can be removed.
