### ISSUE TITLE
wrong lookup for vivado executable

### ISSUE THREAD

**Issue by AnttiLukats** [systemviewinc/visual-system-integrator#207]
systemview_vsi_V2017.4_Release_1.0 is looking for "vivado.exe" in the path, when not found VSI will not start. VSI can be started by creating fake vivado.exe that executes vivado.bat but this is ugly hack.

**Comment by udnaan** [comment]
Hi @AnttiLukats,

This might already be fixed. Can you try the 1.0.1 release and see if the issue presists?

https://s3.amazonaws.com/systemview/files/release/systemview_vsi_V2017.4_Release_1.0.1.tar.bz2

**Comment by AnttiLukats** [comment]
no it is same error with 1.0.1 I am trying to launch VSI using my vivado.exe -> vivado.bat redirector workaround, this allows VSI to be started but then another error comes. So for now it seems Windows is NOT SUPPORTED.

**Comment by udnaan** [comment]
Would you be open to a brief meeting?
We have integration test running on windows so it is only a matter of setting up the environment.

**Comment by AnttiLukats** [comment]
i am pretty much open/available. Here it really looks that any windows work is NOT possible with the 2017.4 release 1.0 or 1.0.1

**Comment by udnaan** [comment]
I have sent you an email on the listed address on your github profile. Looking forward to talking with you.

**Comment by udnaan** [comment]
@AnttiLukats I pushed out a change that should fix this issue. The latest nightly already has this change.

 A smaller patch is attached:
[vsi.zip](https://github.com/systemviewinc/visual-system-integrator/files/2181755/vsi.zip)

Will update with the nightly link once the integration passes. 
Feel free to reopen if the issue remains.

**Comment by udnaan** [comment]
Also the latest nightly link, in case you want to try the whole thing:
https://s3.amazonaws.com/systemview/files/nightly/vsi_20180710_1215.tar.bz2
