### ISSUE TITLE
 in system, hierarchy in hierarchy fails, cxx is wrong

### ISSUE THREAD

**Issue by MenezesM** [systemviewinc/visual-system-integrator#208]
for example, a hierarchy named hier_1, place inside a hierarchy named hier_0, inside zynq_pl the cxx looks like this:

	namespace zynq_pl hier_0 {
		namespace hier_1 {

**Comment by ArtemMarisov** [comment]
Repeating of the issue:
https://github.com/systemviewinc/visual-system-integrator/issues/191
