### ISSUE TITLE
SW Build fails on ubuntu 14.04

### ISSUE THREAD

**Issue by sandeepdutta** [systemviewinc/visual-system-integrator#218]
?????????????
? x86: make ?
?????????????

vsi_sw: Scanning dependencies of target x86
vsi_sw: [ 25%] Building CXX object CMakeFiles/x86.dir/src/main.cxx.o
vsi_sw: [ 50%] Building CXX object CMakeFiles/x86.dir/src/x86.cxx.o
vsi_sw: [ 75%] Linking CXX executable bin/x86
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): invalid relocation type 42
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf64-x86-64.c:343
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): invalid relocation type 42
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf64-x86-64.c:343
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): invalid relocation type 42
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf64-x86-64.c:343
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): invalid relocation type 42
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf64-x86-64.c:343
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): invalid relocation type 42
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf64-x86-64.c:343
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): invalid relocation type 42
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: BFD (GNU Binutils for Ubuntu) 2.24 assertion fail ../../bfd/elf64-x86-64.c:343
vsi_sw: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(net.cxx.o): In function `vsi::runtime::Net::lookup_ipaddr(sockaddr_in*)':
vsi_sw: /home/jenkins/workspace/build/vsi/vsi/target/vsi_runtime/src/net.cxx:69: warning: Using 'getaddrinfo' in statically linked applications requires at runtime the shared libraries from the glibc version used for linking
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: /opt/tools/systemview_vsi_V2017.4_Release_1.0.1/target/X86/lib/libvsi_rt.a(runtime.cxx.o): unrecognized relocation (0x2a) in section `.text._ZN3vsi7runtime7Runtime4initEj'
vsi_sw: /usr/bin/x86_64-linux-gnu-ld: final link failed: Bad value
vsi_sw: collect2: error: ld returned 1 exit status
vsi_sw: make[2]: *** [bin/x86] Error 1
vsi_sw: make[1]: *** [CMakeFiles/x86.dir/all] Error 2
vsi_sw: make: *** [all] Error 2
child process exited abnormally

**Comment by udnaan** [comment]
This is due to 14.04 not having the same version of binutils that we use on our build server. 
Upgrading the binutils should fix that.

```
sudo apt-get install binutils-2.26
```
