### ISSUE TITLE
generate system does not generate correctly SW-HW files if there are no HW blocks

### ISSUE THREAD

**Issue by MenezesM** [systemviewinc/visual-system-integrator#232]
generate system does not generate correctly SW-HW files if there are no HW blocks

driver.sh will be empty
init_hw_io will not have any files

This situation happens when you have system interfaces, in that case you may not have any blocks in the hardware.

**Comment by udnaan** [comment]
Fixed in master. Please verify and close.

**Comment by MenezesM** [comment]
Verified, fixed
