### ISSUE TITLE
Lambda expression confuses vsi_clang

### ISSUE THREAD

**Issue by sandeepdutta** [systemviewinc/visual-system-integrator#235]
The following adds the parameters of the lambda expression cvt_0 to the parameter list of the top level function.

void process_webcam_0(uint32_t oa[WC_IMGSIZE/WC_BPP], hls::stream<int> &cont, hls::stream<int> &ctl)
{
	// wait for the webcam to start streaming
	while (1) {
		if (webcam_0 && webcam_0->running) break;
		sleep(1);
	};
        auto cvt_0 = [] (cv::Mat &in, cv::Mat &out) {
	     cv::cvtColor(in,out,CV_RGB2GRAY);
     };
	// output convertion function : convert to gray scale
	webcam_0->webcam_cvt_process_image(oa,cont,ctl,cvt_0);
}

**Comment by udnaan** [comment]
Should be fixed in master. Verify and close.
