### ISSUE TITLE
execution timer doesn't work with (number)*e(power)

### ISSUE THREAD

**Issue by MenezesM** [systemviewinc/visual-system-integrator#238]
The field in the software import wizard accepts a value like 1e8 but ilang fails then with 

vsi_gen: synax error token 'e8' line 2916
vsi_gen: vsi_ilang: vsi_ilang.y:422: void yyerror(const char*): Assertion `0' failed.

**Comment by sandeepdutta** [comment]
Fixed in vsi_ilang.lex

**Comment by sandeepdutta** [comment]
Fixed
