### ISSUE TITLE
Digital signal processor will be added?

### ISSUE THREAD

**Issue by Mrdwq** [systemviewinc/visual-system-integrator#258]
There is phrase in https://systemviewinc.com/docs/2019.2/introduction/Introduction.html saying"An end system may contains multiple CPUs, FPGAs and DSPs spanning across physical machines from multiple vendors with varying toolsets."
Since X86,ARM-32 bit,ARM-64 bit,ARM-Cortex-R5 are supported currently in VSI, will digital signal processor be supported too?

**Comment by sandeepdutta** [comment]
Hello Mrdwq,

Support for additional processors (such as DSPs) are possible and will be done based on customer needs.
Typically a customers provides us funding for additional features.

Hope that answers your questions.

Best Regards
Sandeep

**Comment by Mrdwq** [comment]
Is it onvenient to answer my other questions about execution context in this issue and in https://github.com/systemviewinc/visual-system-integrator/issues/257? 

Thanks,
mrdwq

**Comment by sandeepdutta** [comment]
Hi Mrdwq,

If there is BUG we will fix it. If the user wants a  specific feature / enhancement then 
we have to evaluate if it makes economic sense. There are some users who are paying for additional 
features.

Best Regards
Sandeep
